# Will only download once
- name: Get Quantum ESPRESSO source
  get_url:
    url: "{{ qe_url }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{  qe_src_archive }}"
  register: qe_download

- name: Extract QE source
  unarchive:
    src: "{{ qe_download.dest }}"
    dest: "{{ globalconfig.vm_codes_folder }}"

- name: Configure QE
  shell: ./configure --enable-parallel
  args:
    creates: "{{ qe_topdir }}/make.inc"
    chdir: "{{ qe_topdir }}"

- name: Make QE executables
  shell: "make {{ item }}"
  args:
    creates: "{{ qe_topdir }}/bin/{{ item }}.x"
    chdir: "{{ qe_topdir }}"
  with_items: "{{ qe_executables }}"
  register: qe_make

- include_tasks: tests.yml
  when: qe_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.bashrc to add QE to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ qe_topdir }}/bin/"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- name: Add Quantum ESPRESSO info (version) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Quantum ESPRESSO"
    option: "version"
    value: "{{ qe_version }}"

- name: Add Quantum ESPRESSO info (location) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Quantum ESPRESSO"
    option: "usage"
    value: >-
        Quantum ESPRESSO is installed in {{ qe_topdir }}. 
        'pw.x', 'cp.x', ... have been added to the PATH
