# Will only download once
- name: Get Quantum ESPRESSO
  get_url: url={{ qe_url }} dest={{ ansible_env.HOME }}/codes/{{ qe_src }}.tar.gz

- name: Unpack Quantum ESPRESSO source files
  shell: "cd {{ ansible_env.HOME }}/codes && tar -xzvf {{ qe_src }}.tar.gz"
  args:
    creates: "{{ qe_topdir }}"

- name: Configure QE
  shell: cd {{ qe_topdir }} && ./configure --enable-parallel
  args:
    creates: "{{ qe_topdir }}/make.inc"

- name: Make QE executables
  shell: "cd {{ qe_topdir }} && make {{ item }}"
  args:
    creates: "{{ qe_topdir }}/bin/{{ item }}.x"
  with_items: "{{ qe_executables }}"

- name: "Put a line in ~/.bashrc to add QE to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ qe_topdir }}/bin/"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- name: Add Quantum ESPRESSO info (version) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Quantum ESPRESSO"
    option: "version"
    value: "{{ qe_version }}"

- name: Add Quantum ESPRESSO info (location) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Quantum ESPRESSO"
    option: "usage"
    value: "Quantum ESPRESSO is compiled and installed in {{ qe_topdir }}. Note that the bin folder is added to the path, so you can just run 'pw.x' (and the same for the other executables) without the need to specify the path"
