yambo_version: "4.2.1"
yambo_src: yambo-{{ yambo_version }}
yambo_src_archive: "{{ yambo_src }}.tar.gz"
yambo_code_folder: "{{ ansible_env.HOME }}"
yambo_url: "https://github.com/yambo-code/yambo/archive/{{ yambo_version }}.tar.gz"
yambo_topdir: "{{ yambo_code_folder }}/{{yambo_src}}"
yambo_executables:
  - yambo
  - p2y
  - ypp
