---
fleur_version: "0.27"
fleur_release: "MaXR2.1"
fleur_src: fleur{{ fleur_release }}
fleur_code_folder: "{{ ansible_env.HOME }}"
fleur_url: "http://www.flapw.de/pm/uploads/FLEUR/{{fleur_src}}.tgz"
fleur_topdir: "{{ fleur_code_folder }}/fleur"
fleur_executables:
  - fleur
  - inpgen
