- name: Install some common editors
  become: true
  apt:
      name: "{{item}}"
      state: present
  with_items:
      - emacs24
      - vim
      - nano
      - evince

- name: install basic .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}"
