---
- name: enable autologin
  become: true
  ini_file: 
    path: /etc/lightdm/lightdm.conf.d/12-autologin.conf
    section: "Seat:*"
    option: "autologin-user"
    value: "{{ customizations_vm_user }}"

- name: disable autologin timeout
  become: true
  ini_file: 
    path: /etc/lightdm/lightdm.conf.d/12-autologin.conf
    section: "Seat:*"
    option: "autologin-user-timeout"
    value: "0"
