- include_tasks: release_notes.yml tags=release-notes
- include_tasks: global_bashrc.yml tags=global-bashrc
- include_tasks: wallpaper.yml tags=wallpaper
- include_tasks: launcher.yml tags=launcher
- include_tasks: disable_autolock.yml tags=disable-autolock
- include_tasks: disable_guestuser.yml tags=disable-guestuser
- meta: flush_handlers
