- name: create mountpoint for shared folder
  become: True
  file:
    path: "{{ globalconfig.vm_shared_folder }}"
    owner: "{{ globalconfig.vm_user }}"
    group: "{{ globalconfig.vm_user }}"
    state: directory

- import_role:
    name: release_notes
  vars:
    section: "{{ globalconfig.vm_name }}"
    option: "shared folder"
    value: >-
      Sharing a folder "/my/folder" with the VM: add folder in VirtualBox
      Settings => Shared Folders as "vbox-folder", then mount it via
      'sudo mount -t vboxsf -o uid=1000,gid=1000 vbox-folder /shared'
    create: true
  when: release_notes is defined and release_notes

