- name: Create folder for generic MARVEL data
  file:
      path: "{{ ansible_env.HOME }}/.local/share/marvelnccr"
      state: directory

- name: Copy the background image
  copy:
      src: marvel-bg.png
      dest: "{{ ansible_env.HOME }}/.local/share/marvelnccr/marvel-bg.png"
      mode: 0755

- name: Create folder for generic MARVEL data in global machine
  become: true
  file:
      path: "/usr/share/marvelnccr"
      state: directory
      mode: 0755

- name: Copy the background image
  become: true
  copy:
      src: marvel-bg.png
      dest: "/usr/share/marvelnccr/marvel-bg.png"
      mode: 0755

- name: add packages (pip)
  become: true
  pip:
    name: "{{item}}"
  with_items:
    # Needed to set the wallpaper (maybe?)
    - psutil

# To work around error:
# Cannot autolaunch D-Bus without X11 $DISPLAY
- name: set the background image
  shell: "DISPLAY=:0.0 dbus-launch --exit-with-session gsettings set org.gnome.desktop.background picture-uri file://{{ ansible_env.HOME }}/.local/share/marvelnccr/marvel-bg.png"
  notify: restart lightdm

- name: set lightdm (login page) not to draw the user background
  become: true
  ini_file: 
    path: /usr/share/glib-2.0/schemas/10_unity-settings-daemon.gschema.override
    section: "com.canonical.unity-greeter"
    option: "draw-user-backgrounds"
    value: "false"
  notify: restart lightdm
  register: lightdm_draw_user_backgrounds

- name: set lightdm (login page) background
  become: true
  ini_file: 
    path: /usr/share/glib-2.0/schemas/10_unity-settings-daemon.gschema.override
    section: "com.canonical.unity-greeter"
    option: "background"
    value: "'/usr/share/marvelnccr/marvel-bg.png'"
  notify: restart lightdm
  register: lightdm_background

# Not sure this is actually needed...
#- name: recreate schemas to apply modifications
#  become: true
#  command: glib-compile-schemas /usr/share/glib-2.0/schemas
#  #when: (lightdm_background.changed) or (lightdm_draw_user_backgrounds.changed)
