---
# Caution: This file is read by vagrant, ansible and bash
vm_version: "2017.10"
vm_name: "MARVEL Virtual Machine"
vm_description: "A VM for computational materials science distributed by the MARVEL NCCR"
vm_url: "https://github.com/marvel-nccr/marvel-virtualmachine"
author: "MARVEL National Centre for Competency in Research"
author_url: "http://nccr-marvel.ch"


# VM configuration
vm_hostname: "marvelvm"
vm_user: "vagrant"
vm_password: "tutorial"
vm_shared_folder: "/shared"
vm_memory: 1024
vm_cpus: 2
vm_vram: 128
release_notes_file: "{{ ansible_env.HOME }}/Desktop/RELEASENOTES.txt"
