---
# Caution: This file is read by vagrant, ansible and bash
vm_version: "18.04.0"
vm_name: "Quantum Mobile"
vm_description: "A Virtual Machine for Computational Materials Science"
vm_url: "https://github.com/marvel-nccr/marvel-virtualmachine"
vm_author: "MARVEL NCCR and MaX CoE"
vm_author_url: "http://nccr-marvel.ch"
vm_release_notes_file: "{{ ansible_env.HOME }}/Desktop/RELEASENOTES.txt"

# VM configuration
vm_hostname: "qmobile"
vm_user: "max"
vm_password: "moritz"
vm_memory: 1024
vm_cpus: 2
vm_vram: 128
vm_shared_folder: "/shared"
vm_codes_folder: "{{ ansible_env.HOME }}/codes"
vm_examples_folder: "{{ ansible_env.HOME }}/examples"
vm_headless: False
vm_browser: chromium # 'chromium' or 'firefox'
