---
# Caution: This file is read by vagrant, ansible and bash
vm_version: "2017.11"
vm_name: "Quantum Mobile"
vm_description: "A Virtual Machine for Computational Materials Science"
vm_url: "https://github.com/marvel-nccr/marvel-virtualmachine"
author: "MARVEL National Centre for Competency in Research and MaX European Centre of Excellence"
author_url: "http://nccr-marvel.ch"

# VM configuration
vm_hostname: "quantum-mobile"
vm_user: "scientist"
vm_password: "quantum-mobile"
vm_memory: 1024
vm_cpus: 2
vm_vram: 128
vm_shared_folder: "/shared"
vm_codes_folder: "{{ ansible_env.HOME }}/codes"
release_notes_file: "{{ ansible_env.HOME }}/Desktop/RELEASENOTES.txt"
vm_examples_folder: "{{ ansible_env.HOME }}/examples"
vm_examples_readme: "{{ ansible_env.HOME }}/examples/README.txt"
