- name: playbook for the MARVEL VM
  hosts: default
  pre_tasks:
    - name: import global variables
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - role: common
      tags: common
    - role: customizations
      tags: customizations
    - role: editors
      tags: customizations
    - role: scheduler
      tags: scheduler
    - role: simulationtools
      tags: simulationtools
  vars:
    # Note: don't use characters that are special for regexps here!
    - reference_point_bashrc_string: "## Add commands before this line if you want them to run also non-interactively"