- name: playbook for the MARVEL VM
  hosts: default
  vars:
    # Note: don't use characters that are special for regexps here!
    - reference_point_bashrc_string: "## Add commands before this line if you want them to run also non-interactively"
    - run_tests: True
    - copy_examples: True
  pre_tasks:
    - name: import global variables
      tags: always
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - role: common
      tags: common
    - role: customizations
      tags: customizations
    - role: editors
      tags: editors
    - role: scheduler
      tags: scheduler
    - role: simulationtools
      tags: simulationtools
    - role: quantum-espresso
      tags: quantum-espresso
    - role: yambo
      tags: yambo
    - role: fleur
      tags: fleur
    - role: siesta
      tags: siesta
    - role: cp2k
      tags: cp2k
    - role: aiida
      tags: aiida
