aiida_tag: "v1.0.0a1"
aiida_extras:
  - rest
  - docs
  - atomic_tools
  - testing
  - notebook
aiida_run_folder: "{{ ansible_env.HOME }}/.aiida_run"
aiida_code_folder: "{{ ansible_env.HOME }}"
aiida_examples_folder: "{{ ansible_env.HOME }}"
aiida_localhost_name: localhost
aiida_localhost_cpus: 2
aiida_venv: "{{ ansible_env.HOME }}/.virtualenvs/aiida"

# postgres
aiida_postgres_user: postgres
aiida_postgres_password: "nnKhpYt5SUjcdmR6"
aiida_postgres_db: aiidadb
aiida_postgres_db_pw: "ne9N_LDK-*JSS"
aiida_postgres_db_user: aiida

# plugins
aiida_plugin_versions:
  aiida_quantumespresso: "v3.0.0a1"
  aiida_fleur: "0.6.0"
  aiida_siesta: "0.11.5"
  aiida_cp2k: "0.9.0"
  aiida_yambo: "0.2.5"
  aiida_wannier90: "1.0.0"

aiida_plugins: "{{ aiida_plugin_versions.keys() }}"

# pseudos
aiida_pseudopotentials:
- name: sssp-pbe-efficiency
  file: SSSP_efficiency_pseudos.aiida
  url: http://archive.materialscloud.org/file/2018.0001/v1
  home_page: http://materialscloud.org/sssp/
  description: >-
   Standard Solid State Pseudopotentials (efficiency) 
   for the PBE functional
- name: sssp-pbe-accuracy
  file: SSSP_accuracy_pseudos.aiida
  url: http://archive.materialscloud.org/file/2018.0001/v1
  home_page: http://materialscloud.org/sssp/
  description: >-
   Standard Solid State Pseudopotentials (accuracy) 
   for the PBE functional
- name: sg15-oncv-1.1
  file: sg15_oncv_upf_2015-10-07.tar.gz
  url: http://www.quantum-simulation.org/potentials/sg15_oncv
  folder: sg15-oncv-1.1
  home_page: http://www.quantum-simulation.org/potentials/sg15_oncv/
  description: >-
   SG15 Optimized Norm-Conserving Vanderbilt (ONCV) pseudopotentials
