# Will only download once
- name: Get Wannier90 source
  get_url:
    url: "{{ wannier90_url }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{  wannier90_src_archive }}"
  register: wannier90_download

- name: Extract Wannier90 source
  unarchive:
    src: "{{ wannier90_download.dest }}"
    dest: "{{ globalconfig.vm_codes_folder }}"
    remote_src: yes

- name: Configure Wannier90
  copy:
    src: "make.inc"
    dest: "{{ wannier90_topdir }}"

- name: Make Wannier90 executables
  shell: "make {{ item.target }}"
  args:
    creates: "{{ wannier90_topdir }}/{{ item.execname }}"
    chdir: "{{ wannier90_topdir }}"
  with_items: "{{ wannier90_executables }}"
  register: wannier90_make

- name: Clean object files
  shell: "rm -f {{ wannier90_topdir }}/src/obj/* {{ wannier90_topdir }}/src/objp/*"
  when: clean is defined and clean

- name: Wannier90 tests
  import_tasks: tests.yml
  when: wannier90_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.bashrc to add W90 to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ wannier90_topdir }}"
    # Do this also non-interactively
    insertbefore: "{{ common_bashrc_string }}"

- import_role:
    name: release_notes
  vars:
    section: "Wannier90"
    option: "version"
    value: "{{ wannier90_version }}"
  when: release_notes

- import_role:
    name: release_notes
  vars:
    section: "Wannier90"
    option: "usage"
    value: >-
        Wannier90 is installed in {{ wannier90_topdir }}. 
        'wannier90.x', 'postw90/x', ... have been added to the PATH
  when: release_notes
