---
# Other roles will check the `release_notes` variable
# to see whether they should include release notes

release_notes_locally: false
release_notes_vm_user: ubuntu
release_notes_vm_path: "/home/{{ release_notes_vm_user }}/RELEASE_NOTES.txt"
release_notes_localhost: "{{ playbook_dir }}/RELEASE_NOTES.txt"
