---
- name: make cp2k topdir
  file:
    dest: "{{ cp2k_topdir }}/exe"
    state: directory

- name: download cp2k binary
  get_url:
    url: "{{ cp2k_binary_url }}"
    dest: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
    mode: "u+x"

- name: symlink binary
  file:
    src: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
    dest: "{{ cp2k_topdir }}/exe/cp2k.ssmp"
    state: link

- name: download cp2k data files
  get_url:
    url: "{{ cp2k_svn_url }}/data/{{ item }}?format=raw"
    dest: "{{ cp2k_topdir }}"
    # for some reason, the first item used to time out
    # with the default timeout of 10s
    timeout: 30
  with_items:
  - BASIS_MOLOPT
  - POTENTIAL
  - ALL_BASIS_SETS
  - ALL_POTENTIALS

- name: download copyright notice
  get_url:
    url: "{{ cp2k_svn_url }}/{{ item }}?format=raw"
    dest: "{{ cp2k_topdir }}"
  with_items:
  - COPYRIGHT
     
- name: "Put a line in ~/.bashrc to add cp2k to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ cp2k_topdir }}/exe"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- import_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k binary was downloaded from source forge.
      simply run 'cp2k.ssmp'
  when: release_notes

