---
- name: make cp2k topdir
  file:
    dest: "{{ cp2k_topdir }}/exe"
    state: directory

- name: download cp2k binary
  get_url:
    url: "{{ cp2k_binary_url }}"
    dest: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
    mode: "u+x"

- name: symlink binary
  file:
    src: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
    dest: "{{ cp2k_topdir }}/exe/cp2k.ssmp"
    state: link


    #- name: download cp2k data files
    #  get_url:
    #    url: "{{ cp2k_svn_url }}/data/{{ item }}?format=raw"
    #    dest: "{{ cp2k_topdir }}"
    #    # for some reason, the first item used to time out
    #    # with the default timeout of 10s
    #    timeout: 30
    #  with_items:
    #  - BASIS_MOLOPT
    #  - POTENTIAL
    #  - ALL_BASIS_SETS
    #  - ALL_POTENTIALS

- name: download cp2k source
  get_url:
    url: "{{ cp2k_url }}"
    dest: "{{ cp2k_code_folder }}"
    # for some reason, the first item used to time out
    # with the default timeout of 10s
    timeout: 60

- name: Extract (only) cp2k data directory
  shell: |
      tar xf {{ cp2k_src_archive }} {{ cp2k_src }}/data
  args:
    chdir: "{{ cp2k_code_folder }}"


- name: download copyright notice
  get_url:
    url: "{{ cp2k_svn_url }}/{{ item }}?format=raw"
    dest: "{{ cp2k_topdir }}"
  with_items:
  - COPYRIGHT
     
- name: "Put a line in ~/.profile to add cp2k to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ cp2k_topdir }}/exe"

- name: "Put a line in ~/.profile for cp2k data directory"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export CP2K_DATA_DIR={{ cp2k_topdir }}/data"

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k binary was downloaded from source forge.
      simply run 'cp2k.ssmp'
  when: release_notes is defined and release_notes

