---
#quite a few dependencies)
# Will only download once
- name: Get cp2k source
  get_url:
    url: "{{ cp2k_url }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{ cp2k_src_archive }}"
  register: cp2k_download

- name: Extract cp2k source
  unarchive:
    src: "{{ cp2k_download.dest }}"
    dest: "{{ globalconfig.vm_codes_folder }}"
    remote_src: yes

- name: Make cp2k executables
  shell: "make -j{{ globalconfig.vm_cpus}} ARCH={{ cp2k_make_arch }} VERSION={{ item }}"
  args:
    chdir: "{{ cp2k_topdir }}/makefiles"
    creates: "{{ cp2k_topdir }}/exe/{{ cp2k_make_arch }}/cp2k.{{ item }}"
  with_items: "{{ cp2k_make_versions }}"
  register: cp2k_make

- include_tasks: tests.yml
  when: cp2k_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.bashrc to add cp2k to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ cp2k_topdir }}/bin"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k was built in {{ cp2k_topdir }}.
      simply run cp2k.popt
