---
# this worked only until it tried rebuilding the package in the ppa
# broken now...
- name: add repo with backport containing recent cp2k version
  become: True
  apt_repository:
    repo: 'ppa:leopold-talirz/xenial-science-backports'
    state: present
    codename: xenial
    update_cache: True

- name: install cp2k {{ cp2k_version }}
  become: True
  apt:
    name: cp2k={{ cp2k_version }}
    state: installed

- import_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k was built via apt.
      simply run cp2k.popt
  when: release_notes

