---
#- import_tasks: install_via_apt.yml
#- import_tasks: install_via_make.yml
- import_tasks: download_binary.yml

- import_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "version"
    value: "{{ cp2k_version }}"
  when: release_notes
