---
#- include_tasks: install_via_apt.yml
#- include_tasks: install_via_make.yml
- include_tasks: download_binary.yml

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "version"
    value: "{{ cp2k_version }}"
  when: release_notes
