---
- name: "install aiida-cp2k-{{ aiida_cp2k_version }} from PyPI"
  pip:
    name: aiida-cp2k
    version: "{{ aiida_cp2k_version }}"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: pip_install.changed

- name: set up cp2k codes for localhost
  include_tasks: code-setup.yml code={{ item }}
  with_items: "{{cp2k_executables}}"
  vars:
   - aiida_code_name:  "cp2k-{{cp2k_version}}"
   - aiida_code_template:  cp2k.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"

- name: Add AiiDA info (codes) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: AiiDA
    option: aiida-cp2k
    value: >-
      aiida-cp2k {{ aiida_cp2k_version }} is installed.
      See 'verdi code list' for available codes.
