---
# extract and prepare oncv
- name: "Create {{ pp.folder }}/"
  file:
    path: "{{ globalconfig.vm_codes_folder }}/{{ pp.folder }}"
    state: directory

- name: "Unpack {{ pp.file }}"
  unarchive:
    src: "{{ aiida_pp_download.dest }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{ pp.folder }}"
    remote_src: True

- name: Copy script to select pseudos
  copy:
    src: oncv-select-pps.sh
    dest: "{{ globalconfig.vm_codes_folder }}/{{ pp.folder }}"

- name: run script to select pseudos
  shell: bash oncv-select-pps.sh
  args:
    chdir: "{{ globalconfig.vm_codes_folder }}/{{ pp.folder }}"

- name: Add upf family
  shell: "{{ aiida_venv }}/bin/verdi data upf uploadfamily {{globalconfig.vm_codes_folder}}/{{ pp.folder }} {{ pp.name }} '{{ pp.description }}'"
