---
- name: "install aiida-quantumespresso-{{ aiida_quantumespresso_version }} from PyPI"
  pip:
    name: aiida-quantumespresso
    version: "{{ aiida_quantumespresso_version }}"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: pip_install.changed

- name: set up QE codes for localhost
  include_tasks: code-setup.yml code={{ item }}
  with_items: "{{qe_executables}}"
  vars:
   - aiida_code_name:  "qe-{{code}}-{{qe_version}}"
   - aiida_code_template:  qe.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"

- include_role:
    name: release_notes
  vars:
    section: "AiiDA"
    option: "aiida-quantumespresso"
    value: >-
      aiida-quantumespresso {{ aiida_quantumespresso_version }} is installed.
      A number of codes are already installed and preconfigured. 
      See 'verdi code list'
  when: release_notes
