---
- name: get AiiDA MaX examples
  git:
    repo: https://github.com/aiidateam/aiida-max-examples.git
    dest: "{{ aiida_examples_folder }}/aiida-max-examples"
    version: master

- name: get AiiDA demos
  git:
    repo: https://github.com/aiidateam/aiida_demos.git
    dest: "{{ aiida_examples_folder }}/aiida-demos"
    version: master
