#- name: Check AiiDA daemon status
#  shell: "{{ aiida_venv }}/bin/verdi daemon status"
#  register: aiida_daemon_status
#  changed_when: False
   
- name: Add AiiDA Daemon as system service
  become: True
  template:
      src: aiida-daemon.service
      dest: /etc/systemd/system
      owner: root 
      group: root 
      mode: 0644

- name: Start AiiDA Daemon system service
  become: True
  systemd:
    name: aiida-daemon
    enabled: true
    masked: no
    daemon-reload: yes
    state: restarted
