# add pseudopotential family
- name: Download "{{ pp.file }}"
  get_url:
    url: "{{ pp.url }}/{{ pp.file }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{ pp.file }}"
    mode: "u+r"
  register: aiida_pp_download

- import_tasks: aiida-pps-sssp.yml
  when: "'sssp' in pp.name and aiida_pp_download.changed"

- import_tasks: aiida-pps-oncv.yml
  when: "'oncv' in pp.name and aiida_pp_download.changed"

- name: Add upf family
  shell: "{{ aiida_venv }}/bin/verdi data upf uploadfamily {{globalconfig.vm_codes_folder}}/{{ pp.folder }} {{ pp.name }} '{{ pp.description }}'"
  when: aiida_pp_download.changed

- import_role:
    name: release_notes
  vars:
    section: "AiiDA"
    option: "{{ pp.name }}"
    value: >-
        pseudopotential family {{ pp.name }}: {{ pp.description }}
        homepage: {{ pp.home_page }}
  when: release_notes
