---
# get the GIT code so we can install a specific branch/tag more easily
- name: Get the AiiDA-quantumespresso code from GIT
  git:
    repo: 'https://github.com/aiidateam/aiida-quantumespresso.git'
    dest: "{{ ansible_env.HOME }}/codes/aiida-quantumespresso"
    version: "{{ aiida_quantumespresso_version }}"
  register: aiida_qe_fetched

# In reinstall and override the pip_install variable, for all extras
- name: "Install AiiDA-quantumepresso from the source package"
  pip:
    name: "file://{{ ansible_env.HOME }}/codes/aiida-quantumespresso"
    editable: True
    virtualenv: "{{ aiida_venv }}"
  register: aiida_qe_installed
  when: aiida_qe_fetched

#- name: "install aiida-quantumespresso-{{ aiida_quantumespresso_version }} from PyPI"
#  pip:
#    name: aiida-quantumespresso
#    version: "{{ aiida_quantumespresso_version }}"
#    virtualenv: "{{ aiida_venv }}"
#  register: aiida_qe_installed

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: aiida_qe_installed.changed

- name: set up QE codes for localhost
  include_tasks: code-setup.yml code={{ item }}
  with_items: "{{quantum_espresso_executables}}"
  vars:
   - aiida_code_name:  "qe-{{code}}-{{quantum_espresso_version}}"
   - aiida_code_template:  qe.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"
  when: quantum_espresso_executables is defined

- import_role:
    name: release_notes
  vars:
    section: "AiiDA"
    option: "aiida-quantumespresso"
    value: >-
      aiida-quantumespresso {{ aiida_quantumespresso_version }} is installed.
  when: release_notes is defined and release_notes
