- name: set up aiida computers
  include_tasks: computer-setup.yml aiida_computer_name={{ item }}
  with_items:
    - "{{ aiida_localhost_name }}"

- import_role:
    name: release_notes
  vars:
    section: "AiiDA"
    option: "computers"
    value: >-
        localhost has already been set up and configured.
        List all available computers with 'verdi computer list -a'
  when: release_notes

