---
- name: Install fleur dependencies
  become: true
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
    - build-essential
    - gfortran
    - gfortran-6
    - g++-6 
    - gcc-6 
    - binutils-gold 
    - git 
    - cmake 
    - libxml2-dev 
    - liblapack-dev 
    - libblas-dev 
    - doxygen

- name: Get fleur source
  unarchive:
    src: "{{ fleur_url }}"
    dest: "{{ globalconfig.vm_codes_folder }}"
    remote_src: yes

  # note: this does not throw an error, even if configure fails...
- name: Configure fleur
  shell: FC=gfortran-6 ./configure.sh AUTO
  args:
    chdir: "{{ fleur_topdir }}"
    creates: "{{ fleur_topdir }}/build/Makefile"

- name: Make fleur executables
  shell: "make"
  args:
    chdir: "{{ fleur_topdir }}/build"
    creates: "{{ fleur_topdir }}/build/fleur"
  register: fleur_make

- include_tasks: tests.yml
  when: fleur_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.bashrc to add fleur to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ fleur_topdir }}/build"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- include_role:
    name: release_notes
  vars:
    section: "fleur"
    option: "version"
    value: "{{ fleur_version }} {{ fleur_release }}"
  when: release_notes

- include_role:
    name: release_notes
  vars:
    section: "fleur"
    option: "usage"
    value: >-
      fleur is compiled and installed in {{ fleur_topdir }}. 
      The folder with executables is added to the path, so simply run 'fleur'
  when: release_notes
