---
# The tmp directory
remote_tmp: '${HOME}/.ansible/tmp'

# The directory where desktop files are stored
default_web_browser_applications_dir: /usr/share/applications

# The directory for the custom XDG config
default_web_browser_custom_config_dir: /etc/xdg/ansible-default-web-browser

# The directory where you can customize the Xsession config
default_web_browser_xsession_d_dir: /etc/X11/Xsession.d

# The directory where custom Xfce4 config is stored
default_web_browser_custom_xfce4_dir: "{{ default_web_browser_custom_config_dir }}/xfce4"

# The directory where custom Xfce4 helpers stored
default_web_browser_custom_xfce4_helpers_dir: "{{ default_web_browser_custom_xfce4_dir }}/helpers"

# The the browser desktop file
default_web_browser_desktop_file: "{{ default_web_browser_applications_dir }}/{{ default_web_browser }}.desktop"

# Temporary desktop file part 1
default_web_browser_tmp_desktop_file_part1: "{{ remote_tmp }}/{{ default_web_browser }}.part1"

# Temporary desktop file part 2
default_web_browser_tmp_desktop_file_part2: "{{ remote_tmp }}/{{ default_web_browser }}.part2"

# Temporary desktop file
default_web_browser_tmp_desktop_file: "{{ remote_tmp }}/{{ default_web_browser }}.desktop"
