- name: Install plotting tools, etc.
  become: true
  apt:
      name: "{{ item }}"
      state: installed
  with_items:
    # For AiiDA
    - libffi-dev
    - libssl-dev
    - graphviz
    # For plotting
    - grace
    - gnuplot
    - python-tk 
    - xcrysden
    # note: jmol+java = 110MB
    - jmol
    - default-jre

- name: Add plotting tools info to release notes
  include_role: 
    name: release_notes
  vars:
    section: "Plotting Tools"
    option: "available tools"
    value: "xmgrace, gnuplot, xcrysden, jmol"
