---
siesta_version: "4.0.1"
siesta_minor_version: "4.0"
siesta_src: siesta-{{ siesta_version }}
siesta_url: "https://launchpad.net/siesta/{{ siesta_minor_version }}/{{ siesta_version }}/+download/{{ siesta_src }}.tar.gz"
siesta_topdir: "{{ globalconfig.vm_codes_folder }}/siesta-{{ siesta_version }}"
siesta_executables:
  - siesta
release_notes_file: "{{ globalconfig.release_notes_file }}"

siesta_tests:
- h2o
