aiida_version: "0.10.0rc1"
aiida_extras:
  - REST
  - docs
  - atomic_tools
  - testing
  - notebook
aiida_run_folder: "{{ ansible_env.HOME }}/.aiida_run"
aiida_localhost_name: localhost
postgres_pw: "ne9N_LDK-*JSS"
postgres_db: aiidadb
postgres_user: aiida
aiida_venv: "{{ ansible_env.HOME }}/.virtualenvs/aiida"

# plugins
aiida_fleur_version: "0.5.0"
aiida_siesta_version: "0.9.7.1"
aiida_cp2k_version: "0.2.2"
aiida_yambo_version: "0.2-beta"

# examples
aiida_examples:
- TiO2
