qe_version: "6.2"
qe_src: "q-e-6.2-d"
qe_src_archive: "{{ qe_src }}.tar.gz"
#qe_url: "http://www.qe-forge.org/gf/download/frsrelease/240/1075/{{qe_src_archive }}"
qe_url: "https://github.com/QEF/q-e/archive/v6.2+d.tar.gz"

qe_topdir: "{{ globalconfig.vm_codes_folder }}/{{qe_src}}"
qe_executables:
  - pw
  - cp
  - pp
  - ph
  - neb
