- name: testing ansible environment
  debug:
    msg: Connecting to host {{ inventory_hostname }} as user {{ ansible_user }}

- name: test variable
  debug:
    msg: "RUNNING SCRIPT FOR VM VERSION {{ globalconfig.vm_version }}"
