- include_tasks: debug.yml
# This is now handled by vagrant
#- include_tasks: password.yml
- include_tasks: bashrc_refpoint.yml
- include_tasks: swap.yml
- include_tasks: packages.yml
- include_tasks: hostname.yml
- include_tasks: start_services.yml
- include_tasks: timezone.yml
