- name: Update repositories cache & upgrade packages
  become: true
  apt:
      update_cache: yes
      upgrade: yes
      cache_valid_time: 86400 #One day

- name: Install ubuntu-desktop (apt)
  become: true
  apt:
      name: "{{item}}"
      state: latest
  with_items:
      - ubuntu-desktop
      - python-pip
      - python-dev
  notify: apt clean

- name: upgrade pip
  become: true
  pip: 
    name: pip
    extra_args: --upgrade
  notify: clean cache

- name: add packages (pip)
  become: true
  pip: 
    name: "{{item}}"
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: "Run virtualenvwrapper once to create folders"
  shell: "source /usr/local/bin/virtualenvwrapper.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.virtualenvs/initialize"

# This fixes https://github.com/marvel-nccr/marvel-virtualmachine/issues/21
- name: "Fix virtualenvwrapper python executable"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- name: "Activate the virtualenvwrapper for the user"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source /usr/local/bin/virtualenvwrapper.sh"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"
