 # On MacOS this requires the passlib python module
- name: Changing password for {{ globalconfig.vm_user }}
  become: True
  user: 
    name: "{{ globalconfig.vm_user }}"
    password: "{{ globalconfig.vm_password |password_hash('sha512') }}"
