- name: Install ubuntu-desktop (apt)
  become: true
  apt:
      name: "{{item}}"
      state: latest
  with_items:
      - ubuntu-desktop
      #- lxde
      #- lxde-common
  notify: apt clean

- name: Start lightdm service to get a graphical login
  become: true
  service:
    name: lightdm
    state: started

- name: install chromium-browser
  become: true
  apt:
      name: "chromium-browser"
      state: latest
  notify: apt clean
  when: common_browser == 'chromium'

- name: 
  import_role: 
    name: gantsign.default-web-browser
  vars:
    default_web_browser: chromium-browser
  when: common_browser == 'chromium'
